### PR TITLE
introduce softmax option for slpLMSnet - fixes #5

### LINKED ISSUE #5: slpLMSnet - p's do not sum to one with multiple outcomes?
Ivan Ivanchei reports (email) that when using slpLMSnet as a multi-outcome networks, the response probability vector (p) does not sum to one ... which it probably should?

### PR DESCRIPTION
**Pull request by lenarddome**
Fixes #5 by introducing a softmax option for slpLMSnet.

### CODE REVIEW

**Comment by ajwills72** [comment]
Looking good, except that unit test does not test new functionality. I suggest doing something like adding a second test within the test_slpLMSnet.R code where the option is 'softmax'. Have a go, let me know, and I'll proceed to test and roll into master.

**Comment by lenarddome** [comment]
Great! Thank you for the review. Seems like a weird thing to miss on my part.

**I modified the unit test, so now it tests new functionality.**

**Comment by ajwills72** [comment]
Similar issue as for dissectEXIT - Rdata not updated recently, so test fails:

Screenshot from 2022-01-05 16-49-14

**Comment by lenarddome** [comment]
Okay. Added new `test_slpLMSnet.RData` file to test unit.

Tests passed on my local run, GitHub has all the latest updates, so you should have no problem with compiling and checking now. 🤞

**Pull request merged**
